[window]
title = "Terminal"
blur = true
opacity = 0.75
dynamic_padding = true
option_as_alt = "Both"

[window.padding]
x = 0
y = 0

[window.dimensions]
columns = 160
lines = 80

[cursor.style]
shape = "Block"
blinking = "Never"

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0
glyph_offset = { x = 0, y = 0 }

[font.normal]
family = "AgaveNerdFontMono"
style = "Regular"

[font.bold]
family = "AgaveNerdFontMono"
style = "Bold"

[font.italic]
family = "AgaveNerdFontMono"
style = "Regular"

[font.bold_italic]
family = "AgaveNerdFontMono"
style = "Bold"

[keyboard]
bindings = [
  { key = "Key0", mods = "Command", action = "ResetFontSize" },
  { key = "Equals", mods = "Command", action = "IncreaseFontSize" },
  { key = "Plus", mods = "Command", action = "IncreaseFontSize" },
  { key = "NumpadAdd", mods = "Command", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Command", action = "DecreaseFontSize" },
  { key = "NumpadSubtract", mods = "Command", action = "DecreaseFontSize" },
  { key = "C", mods = "Command", action = "Copy" },
  { key = "V", mods = "Command", action = "Paste" },
  { key = "H", mods = "Command", action = "Hide" },
  { key = "Q", mods = "Command", action = "Quit" },
  { key = "W", mods = "Command", action = "Quit" },
  { key = "N", mods = "Command", action = "SpawnNewInstance" },
  { key = "T", mods = "Command", action = "SpawnNewInstance" },
  { key = "F", mods = "Command|Control", action = "None" },
  { key = "F", mods = "Command", mode = "~Search", action = "None" },
  { key = "A", mods = "Command", action = "None" },
  { key = "B", mods = "Command", mode = "~Search", action = "None" },
  { key = "F", mods = "Command|Shift", action = "ToggleFullscreen" },
  { key = "Return", mods = "Shift", chars = "\u001b[13;2u" },
]

[colors.primary]
background = "0x191724"
foreground = "0xe0def4"

[colors.cursor]
text = "0x191724"
cursor = "0xe0def4"

[colors.vi_mode_cursor]
text = "0x191724"
cursor = "0x31748f"

[colors.selection]
text = "0x191724"
background = "0x403d52"

[colors.normal]
black = "0x191724"
red = "0xeb6f92"
green = "0x31748f"
yellow = "0xf6c177"
blue = "0x9ccfd8"
magenta = "0xc4a7e7"
cyan = "0xebbcba"
white = "0xe0def4"

[colors.bright]
black = "0x26233a"
red = "0xeb6f92"
green = "0x31748f"
yellow = "0xf6c177"
blue = "0x9ccfd8"
magenta = "0xc4a7e7"
cyan = "0xebbcba"
white = "0xe0def4"
