[window]
title = "Terminal"
decorations = "none"
blur = true
opacity = 0.75
padding.x = 10
padding.y = 10

[window.dimensions]
columns = 160
lines = 80

[cursor.style]
shape ="Block"
blinking = "Never"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
glyph_offset = { x = 0, y = 0 }
normal.family = "AgaveNerdFontMono"
normal.style = "Regular"
size = 12.0

[font.bold]
family = "AgaveNerdFontMono"
style = "Bold"

[font.italic]
family = "AgaveNerdFontMono"
style = "Italic"

[keyboard]
bindings = [
	{ key = "T", mods = "Control", action = "CreateNewTab" },
	{ key = "T", mods = "Control|Shift", action = "CreateNewWindow" },
	{ key = "T", mods = "Control|Alt|Shift", action = "SpawnNewInstance" },
	{ key = "C", mods = "Control", action = "Copy" },
	{ key = "V", mods = "Control", action = "Paste" },
	{ key = "Equals", mods = "Control|Shift", action = "IncreaseFontSize" },
	{ key = "Minus", mods = "Control", action = "DecreaseFontSize" },
	{ key = "W", mods = "Control", action ="Hide" },
	{ key = "W", mods = "Control|Shift", action ="Minimize" },
	{ key = "W", mods = "Control|Alt|Shift", action ="Quit" },
]
