general {
    lock_cmd = ~/.config/hypr/scripts/session-event.sh lock
    before_sleep_cmd = ~/.config/hypr/scripts/session-event.sh before-sleep
    after_sleep_cmd = ~/.config/hypr/scripts/session-event.sh after-sleep
}

listener {
    timeout = 300
    on-timeout = ~/.config/hypr/scripts/session-event.sh lock
}

listener {
    timeout = 330
    on-timeout = ~/.config/hypr/scripts/session-event.sh sleep
    on-resume = ~/.config/hypr/scripts/session-event.sh wake
}

