preload = ~/.config/hypr/images/left.jpg
preload = ~/.config/hypr/images/middle.jpg
preload = ~/.config/hypr/images/right.jpg

wallpaper {
    monitor = DP-2
    path = ~/.config/hypr/images/left.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = ~/.config/hypr/images/middle.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/images/right.jpg
    fit_mode = cover
}

splash = false
