set -a terminal-features "tmux-256color:RGB"
set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi
set -g status-position top
set -g status-justify absolute-centre

# Rose Pine Theme
set -g status-style "bg=#191724 fg=#e0def4"
set -g window-status-style "bg=#191724 fg=#6e6a86"
set -g window-status-current-style "bg=#191724 fg=#31748f bold"
set -g window-status-activity-style "bg=#191724 fg=#eb6f92"
set -g message-style "bg=#26233a fg=#e0def4"
set -g pane-border-style "fg=#403d52"
set -g pane-active-border-style "fg=#31748f"
set -g mode-style "bg=#31748f fg=#191724"
set -g status-interval 5
set -g status-left "#S"
set -g status-right ""
set -g mouse on


bind r source-file "~/.config/tmux/tmux.conf"
bind-key -n S-Left swap-window -t -1\; select-window -t -1
bind-key -n S-Right swap-window -t +1\; select-window -t +1
bind b set -g status
bind E show-environment -g

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

run '~/.tmux/plugins/tpm/tpm'
